### ISSUE TITLE
Programs compiled by C++ cross compiler cannot handle exceptions

### ISSUE THREAD

**Issue by trungnt2910** [jessicah/cross-compiler#1]
## Steps to reproduce:
- Build the cross-compiler toolchain on a fresh Ubuntu instance.
```sh
export BUILDROOT=$HOME/builds/cross-compiler
git clone https://github.com/jessicah/cross-compiler
cd cross-compiler && ./build-rootfs.sh x86_64 --rootfsdir $BUILDROOT
# make the Haiku cross-compiler available
export PATH=$PATH:$BUILDROOT/generated/cross-tools-x86_64/bin
```
- Confirm that `g++` is built:
```sh
x86_64-unknown-haiku-g++ --version
```
Outputs:
```
x86_64-unknown-haiku-g++ (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- Create a file at `$HOME`, named `hello_world.cpp`, with this content:
```cpp
#include <iostream>
#include <stdexcept>

void foo()
{
    throw std::exception();
}

int main()
{
    try
    {
        foo();
    }
    catch (const std::exception&)
    {
        std::cout << "Hello World!" << std::endl;
    }
    return 0;
}
```
- Build it using the native Linux compiler, and run:
```sh
g++ ~/hello_world.cpp -o ~/hello_world && ~/hello_world
```
Outputs:
```
Hello World!
```
- Build it using the Linux cross-compiler for Haiku, copy it to a Haiku machine, and run:
```sh
x86_64-unknown-haiku-g++ ~/hello_world.cpp -o ~/hello_world && ~/hello_world
```
Outputs, on a Haiku machine:
```
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Abort
Kill Thread
```

## Notes:
The same code when built natively on Haiku works well. It only fails when cross-compiled from Linux.

**Comment by jessicah** [comment]
It's not linking to `libgcc_s.so`, not sure why, seems to be embedding own exception handling into the binary, but explicitly adding `-lgcc_s` appears to resolve the issue.

eng/common/cross/toolchain.cmake:259 might be sufficient to add `-lgcc_s` there

**Comment by trungnt2910** [comment]
`x86_64-unknown-haiku-g++ hello_world.cpp -o hello_world -lgcc_s`

still creates a binary that fails to run on Haiku, with the same output.
```
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Abort
Kill Thread
```

**Comment by trungnt2910** [comment]
Somehow `-lgcc_s` resolves into this:
```
/home/trung/builds/cross-compiler/boot/system/develop/lib/libgcc_s.so.1
```
instead of simply `libgcc_s.so.1` like a native binary on Haiku.
