### ISSUE TITLE
Build failure with current Haiku

### ISSUE THREAD

**Issue by johnsonjh** [jessicah/cross-compiler#4]
```sh
BUILD FAILURE:
...failed updating 1 target(s)...
...skipped 4 target(s)...
...updated 282 target(s)...
HaikuRepository1 objects/haiku/x86_64/packaging/repositories/Haiku
../tmp/haiku/build/scripts/build_haiku_repository: line 13: objects/haiku/x86_64/packaging/repositories/Haiku-repository-init-vars: No such file or directory

../tmp/haiku/build/scripts/build_haiku_repository "objects/haiku/x86_64/packaging/repositories/Haiku-repository-init-vars" "objects/haiku/x86_64/packaging/repositories/Haiku" "objects/haiku/x86_64/packaging/repositories/Haiku-info" "objects/haiku/x86_64/packaging/packages/haiku.hpkg" "objects/haiku/x86_64/packaging/packages/haiku_datatranslators.hpkg" "objects/haiku/x86_64/packaging/packages/haiku_devel.hpkg" "objects/haiku/x86_64/packaging/packages/haiku_loader.hpkg" "objects/haiku/x86_64/packaging/packages/haiku_extras.hpkg" "objects/haiku/x86_64/packaging/packages/makefile_engine.hpkg" "objects/haiku/x86_64/packaging/packages/netfs.hpkg" "objects/haiku/x86_64/packaging/packages/userland_fs.hpkg" "objects/haiku/x86_64/packaging/packages/webpositive.hpkg"

...failed HaikuRepository1 objects/haiku/x86_64/packaging/repositories/Haiku ...

BUILD FAILURE:
...failed updating 1 target(s)...
```

**Comment by jessicah** [comment]
I haven't modified this file. Did you start from a clean build after updating this repo? It's possible your generated directory is in an invalid state.

I've run the build multiple times now to completion.

**Comment by johnsonjh** [comment]
Strange, I've run it three times on two different machines and it fails in the same place.  I do have a complete build log but it is huge.

Building from a fresh clone of this repo and `./build-rootfs.sh x86_64 --jobs 4 --rootfsdir x86_64-unknown-haiku`

**Comment by johnsonjh** [comment]
Ah it seems the actual error is further up ...

```
...found 105803 target(s)...
...updating 15977 target(s)...
Link objects/linux/x86_64/release/build/libroot/libroot_build.so
/usr/bin/ld: cannot find -lsupc++: No such file or directory                                                                collect2: error: ld returned 1 exit status
```

**Comment by jessicah** [comment]
You do have the GNU C++ library development package installed on your system, right?

**Comment by johnsonjh** [comment]
That was solved by installing libstdc++-devel-14.2.1-1.fc40.i686 in addition to the x86_64 package.  No idea why that might be, but it is!

I am now getting another error (--retry-on-host-error invalid) but this is Haiku's fault.  Fedora has updated to wget2, which no longer has this option.  I'll fix that and report upstream. 

I hope it'll finish now ...

**Comment by johnsonjh** [comment]
all good now, I'll close

**Comment by jessicah** [comment]
Is wget2 symlinked as wget on Fedora? I'm also a Haiku dev, looking at how might detect which wget the system is using...

**Comment by johnsonjh** [comment]
Yes, I just the jamfile rules to not use those wget option.  

Fedora switched "wget" to be wget2 as of Fedora 40.  

It might make more sense to add a curl fallback to that too, before the || exit 1 in the jamfile rules.
